### ISSUE TITLE
Error installing tensorflow2.5.0

### ISSUE THREAD

**Issue by justinesjw** [yafi38/scGIST#12]
Hi, 

Thanks for building scGIST! 

I am currently facing difficulty installing it because `tensorflow==2.5.0` using Python 3.9.13 on macOS Sequoia 15.1, 

<img width="569" alt="image" src="https://github.com/user-attachments/assets/f4b3e5b3-653e-4152-b444-2f3668a5014f">

It also doesn't work when I install it in a python environment. I think this is because I do not have GPU and the later versions of tensorflow requires GPU.

How can I solve this? I can only install tensorflow 2.18.0 is there any way I can use this version when running scGIST? 

Thank you, 
Justine

**Comment by yafi38** [comment]
Hi @justinesjw. From the error log, it looks like the selected python version is 2.1.0. Could you please confirm which python version you are using while installing tensorflow?

**Comment by justinesjw** [comment]
Hi @yafi38 

Thanks! this issue is solved
