### ISSUE TITLE
Error in gist.create_model()

### ISSUE THREAD

**Issue by justinesjw** [yafi38/scGIST#13]
Hi! 

Thanks for building scGIST! 

I am stuck at the step where I create a model. I get this error --> 
![image](https://github.com/user-attachments/assets/fc1f5fc8-659e-4c74-8237-e7a666a771da)

How can I fix this error? 

Best, 
Justine

**Comment by yafi38** [comment]
Hi @justinesjw.

Sorry for the late response. Are you still facing this issue?

**Comment by justinesjw** [comment]
Hi @yafi38 

Thanks! I solved that when I properly installed it. 

But now I'm facing this error
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/98e7b01b-f6d7-429e-badf-aa81ffa91b81">

May I know how I can fix this issue?

Best, 
Justine

**Comment by yafi38** [comment]
Hi @justinesjw 

We currently do not support sparse matrices. You will need to convert the sparse matrices to dense matrices. Hope it will help.

Thanks.

**Comment by justinesjw** [comment]
Hi @yafi38, 

Thanks! the issue is resolved!

Best, 
Justine
