### ISSUE TITLE
How should priority be specified?

### ISSUE THREAD

**Issue by pakiessling** [yafi38/scGIST#6]
Hi, thank you for the package.
I especially like the ability to prioritize certain genes or receptor ligand pairs.

Can you elaborate a little bit more on how this should be specified?

I assume this should be a float between 0 and 1?

What would 0 do, what would 1 do?

If I have genes that I am certain I want they would be 1? and genes that won't work should be 0?

I am also thinking about discouraging very highly expressed genes because of optical crowding. Would it make sense to map expression levels to a value between 0 and 1 and supplying this to the algorithm?

Thank you!

**Comment by yafi38** [comment]
Hi. 

Yes, the priority should be a float between 0 and 1. 
0 means low priority and 1 means high priority. 
The higher the priority, the more likely the gene is going to be picked by the model.
This is a tool and the user may use it the way they seem fit. If you certainly want a gene, you can give it higher priority. If you do not want some particular genes, you can give them 0 priority and increase the priority of other genes. So those genes will have relatively lower priority.

Also, currently the way we can give priority of the gene is to create a list of numbers. Where the `i-th` index item will correspond to the priority of the `i-th` gene in the dataset.

If you have any more questions please feel free to ask them. 

Thank you.
