### ISSUE TITLE
Installation failed - Suggestion to move to add pip compatibility instead of setup.py

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [yafi38/scGIST#8]
Hey, great tool! I was trying to use it, but the installation can be quite challenging specially using setup.py. Do you have plans on moving the installation to pip instead? Would be much easier to debug as well since I'm getting this error:

`RuntimeError: Running cythonize failed!`

**Comment by yafi38** [comment]
Hi @Rafael-Silva-Oliveira. Sorry to hear that. Could you please use the `requirements.txt` file attached to this comment. This may include some extra packages. But hopefully, it will work.
[requirements.txt](https://github.com/yafi38/scGIST/files/15419788/requirements.txt)

**Comment by yafi38** [comment]
Hi @Rafael-Silva-Oliveira.

Were you able to install the required packages using the `requirements.txt` file? If not, you can use the following one.

[requirements.txt](https://github.com/user-attachments/files/16044786/requirements.txt)

**Comment by Rafael-Silva-Oliveira** [comment]
Hello, I was able to eventually get it to work before using the requirements files, but it doesn't seem to be compatible with Visium HD data (600k bins, 18k genes, it kills the terminal with memory error, even running on a server), so I'm afraid this package isn't suitable for HD ST data, but thank you though! :)
